image: "python:3.7"

stages:
  - prepare
  - test
  - release-snapshot
  - release-tag

variables:
  BUILD_TAG: $CI_COMMIT_TAG
  COMPOSE_INTERACTIVE_NO_CLI: 1

env:
  stage: prepare
  script:
    - pip install -r requirements.txt
    - pip install -r dashboard/requirements.txt

checks:
  stage: test
  script:
    - pip install pycodestyle
    - bin/lint

test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  script:
    - ls -lah
    - pwd
    - apk add --no-cache bash docker-compose
    - tests/run_tests


release-snapshot:dev:
  stage: release-snapshot
  image: docker:latest
  services:
    - docker:dind
  script:
    - apk add --no-cache bash
    - bash bin/deploy_to_dockerhub dev
  only:
    - master

release-tag:release:
  stage: release-tag
  image: docker:latest
  services:
    - docker:dind
  only:
    - tags
  script:
    - apk add --no-cache bash
    - bash bin/deploy_to_dockerhub "$BUILD_TAG" latest
