language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r dashboard/requirements.txt

script:
  - bin/test
  - bin/lint

deploy:
  - provider: script
    script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSSWORD"
    - bin/api_package_docker "$TRAVIS_TAG"
    - bin/dashboard_package_docker "$TRAVIS_TAG"
    on:
      tags: true
      #branch: master

