version: '3'
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysterium-api
    ports:
      - 8001:80
    environment:
      DB_HOST: mysterium-mysql
      DB_NAME: myst_api
      DB_USER: myst_api
      DB_PASSWORD: myst_api
    volumes:
      - .:/code
    depends_on:
      - db

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: mysterium-dashboard
    ports:
      - 8002:80
    environment:
      DB_HOST: mysterium-mysql
      DB_NAME: myst_api
      DB_USER: myst_api
      DB_PASSWORD: myst_api

    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: percona:5.7
    container_name: mysterium-mysql
    restart: always
    ports:
      - 33061:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myst_api
      MYSQL_USER: myst_api
      MYSQL_PASSWORD: myst_api
