FROM python:2.7

WORKDIR /code/dashboard

ADD dashboard/requirements.txt .
RUN pip install -r requirements.txt

ADD dashboard .
ADD models.py .
ADD settings.py .

ENTRYPOINT ["python", "server.py"]
EXPOSE 8080
