version: '3'
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysterium-api
    ports:
      - 8001:80
    environment:
      APP_PORT: 80
      DB_HOST: mysterium-mysql
      DB_NAME: testnet_api
      DB_USER: testnet_api
      DB_PASSWORD: testnet_api
      DISCOVERY_VERIFY_IDENTITY: "false"
    volumes:
      - .:/code
    depends_on:
      - db

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: mysterium-dashboard
    ports:
      - 8002:80
    environment:
      APP_PORT: 80
      API_HOST: http://api
      DB_HOST: mysterium-mysql
      DB_NAME: testnet_api
      DB_USER: testnet_api
      DB_PASSWORD: testnet_api
    volumes:
      - .:/code
    depends_on:
      - db

  db:
    image: percona:5.7
    container_name: mysterium-mysql
    restart: always
    command: ['--event-scheduler=ON']
    ports:
      - 33061:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testnet_api
      MYSQL_USER: testnet_api
      MYSQL_PASSWORD: testnet_api
    healthcheck:
      test: mysqladmin ping --silent
      interval: 5s
      timeout: 5s
      retries: 15

volumes:
  db-data:
