FROM python:2.7

WORKDIR /code/dashboard

ADD dashboard/requirements.txt .
RUN pip install -r requirements.txt

ADD dashboard /code/dashboard
ADD models.py /code/models.py
ADD queries.py /code/queries.py
ADD settings.py /code/settings.py

ENTRYPOINT ["python", "server.py"]
