"""empty message

Revision ID: 1f8c96198632
Revises: cf06348b408d
Create Date: 2020-04-16 07:22:09.264469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f8c96198632'
down_revision = 'cf06348b408d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitoring_failed', sa.Column('service_type', sa.String(length=255), nullable=False))
    op.drop_constraint('monitoring_failed_ibfk_1', 'monitoring_failed', type_='foreignkey')
    op.create_foreign_key(None, 'monitoring_failed', 'node', ['provider_id', 'service_type'], ['node_key', 'service_type'])
    op.drop_index(op.f('PRIMARY'), table_name='monitoring_failed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'monitoring_failed', type_='foreignkey')
    op.create_foreign_key('monitoring_failed_ibfk_1', 'monitoring_failed', 'node', ['provider_id'], ['node_key'])
    op.drop_column('monitoring_failed', 'service_type')
    # ### end Alembic commands ###
