"""Affiliates table and email field in identity_registration

Revision ID: 22dafaa1f597
Revises: 9e41c86dc8e3
Create Date: 2019-07-09 12:17:14.222244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22dafaa1f597'
down_revision = '9e41c86dc8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('payout_eth_address', sa.String(length=42), nullable=True),
    sa.Column('referral_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('identity_registration', sa.Column('email', sa.String(length=254), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identity_registration', 'email')
    op.drop_table('affiliates')
    # ### end Alembic commands ###
