"""empty message

Revision ID: 441fd5fc94a1
Revises: e73480955f62
Create Date: 2020-01-16 09:14:20.683599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '441fd5fc94a1'
down_revision = 'e73480955f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments_tokens',
    sa.Column('provider_id', sa.String(length=42), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tokens', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('provider_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments_tokens')
    # ### end Alembic commands ###
