"""add country columns

Revision ID: 5692855d1037
Revises: 6230c14fa5df
Create Date: 2018-02-09 09:09:21.571186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5692855d1037'
down_revision = '6230c14fa5df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('country', sa.String(length=255), nullable=True))
    op.add_column('session', sa.Column('client_country', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'client_country')
    op.drop_column('node', 'country')
    # ### end Alembic commands ###
