"""Add session.consumer_id

Revision ID: 6230c14fa5df
Revises: 9f7a13ec4cef
Create Date: 2018-01-12 16:25:22.565704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6230c14fa5df'
down_revision = '9f7a13ec4cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('consumer_id', sa.String(length=42), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'consumer_id')
    # ### end Alembic commands ###
