"""empty message

Revision ID: 9e41c86dc8e3
Revises: 1d68447aed59
Create Date: 2019-06-07 12:14:19.932567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e41c86dc8e3'
down_revision = '1d68447aed59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identity_registration', sa.Column('referral_code', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identity_registration', 'referral_code')
    # ### end Alembic commands ###
